### ISSUE TITLE
platform specific project

### ISSUE THREAD

**Issue by craigryan** [kitconcept/webpack-starter-angular#14]
I can't use this starter project at all since you're using npm to drive builds via script commands which are platform specific. Building on windows and running on linux/macos is an everyday event. I'm afraid 'export NODE_ENV=dev && webpack' doesn't cut it. Nor does my bothering to hack this to a windows "set NODE_ENV...." equivalent because 'npm run start' still fails to generate even a working index.html since it contains nothing more than "TypeError: Path must be a string. Received undefined".

I can't see any benefit to go with platform specific projects especially for modern front end applications. I suggest you simply provide a proper build (gulp) so more of us can use your template.

**Comment by tisto** [comment]
@craigryan seriously?

**Comment by craigryan** [comment]
ya, seriously. DIsappointing response, not likely to win me over.

**Comment by tisto** [comment]
@craigryan good! Please go away. I share this because some people might find it useful, if not I don't mind. There are thousand of other JS seed projects you can choose from. 

I just don't have time to discuss with 12 year old kids, who think that Windows is a decent development platform and gulp is a state-of-the-art JS bundler...
